"""add created_at to messages

Revision ID: 666f44fd54dd
Revises: b0f9ec3cd47f
Create Date: 2026-07-07 19:11:34.552759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666f44fd54dd'
down_revision: Union[str, Sequence[str], None] = 'b0f9ec3cd47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
